- hosts: raspi
  remote_user: pi
  roles:
    - { role: role/apt }
    - { role: role/erlang }
    - { role: role/elixir }
  tasks:
    - name: install packages
      apt: name={{item}} state=present
      become: yes
      with_items:
        - vim
        - git
